# Generated by Django 5.0.1 on 2024-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom du coordonnateur')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prenom du coordonnateur')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('full_name_of_coordinator_position', models.CharField(max_length=255, verbose_name='Nom complet du poste')),
                ('word_from_the_coordinator', models.TextField(max_length=5000, verbose_name='Mot du coordonnateur')),
                ('biography', models.TextField(max_length=5000)),
                ('image_coordinator', models.ImageField(upload_to='Coordonnateur_image/', verbose_name='Photo du coordonateur')),
            ],
            options={
                'verbose_name_plural': 'Coordonnateur',
            },
        ),
    ]
