# Generated by Django 5.0.1 on 2024-06-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name_plural': 'Coordonnateurs'},
        ),
        migrations.AddField(
            model_name='coordinator',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='En fonction actuellement'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='biography',
            field=models.TextField(max_length=5000, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Prénom du coordonnateur'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='image_coordinator',
            field=models.ImageField(upload_to='Coordonnateur_image/', verbose_name='Photo du coordonnateur'),
        ),
    ]
