# Generated by Django 5.0.1 on 2024-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_coordinator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name_plural': 'Coordonnateur'},
        ),
        migrations.AddField(
            model_name='coordinator',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
