# Generated by Django 5.0.1 on 2024-06-11 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de publication'),
        ),
    ]
